-- MySQL Script generated by MySQL Workbench
-- ter 26 out 2021 19:55:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Zoologico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS Zoologico;
-- -----------------------------------------------------
-- Schema Zoologico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Zoologico` ;
USE `Zoologico` ;

-- -----------------------------------------------------
-- Table `Zoologico`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zoologico`.`animais` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `nome_animal` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `idade` INT NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_animal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zoologico`.`gerentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zoologico`.`gerentes` (
  `id_gerente` INT NOT NULL AUTO_INCREMENT,
  `nome_gerente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gerente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zoologico`.`cuidadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zoologico`.`cuidadores` (
  `id_cuidador` INT NOT NULL AUTO_INCREMENT,
  `nome_cuidador` VARCHAR(45) NOT NULL,
  `id_gerente` INT NOT NULL,
  PRIMARY KEY (`id_cuidador`),
    FOREIGN KEY (`id_gerente`)
    REFERENCES `Zoologico`.`gerentes` (`id_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zoologico`.`cuida_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zoologico`.`cuida_animal` (
  `id_cuidador` INT NOT NULL,
  `id_animal` INT NOT NULL,
  INDEX `cuidador_idx` (`id_cuidador` ASC) INVISIBLE,
  CONSTRAINT `cuidador`
    FOREIGN KEY (`id_cuidador`)
    REFERENCES `Zoologico`.`cuidadores` (`id_cuidador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `animal`
    FOREIGN KEY (`id_animal`)
    REFERENCES `Zoologico`.`animais` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
